

services:
  web:
    build:
      context: .
      target: frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  api:
    build:
      context: .
      target: backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - ./server/yolo_model/best.pt:/app/server/yolo_model/best.pt
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge