version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      args:
        - PIP_NO_CACHE_DIR=1
        - PIP_DISABLE_PIP_VERSION_CHECK=1
    container_name: vcs-backend
    hostname: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/yolo_model:/app/yolo_model
      - /app/__pycache__
    restart: unless-stopped
    networks:
      - vcs-network
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - ULTRALYTICS_SKIP_CHECK=1

  frontend:
    build: 
      context: ./frontend
      args:
        - NPM_CONFIG_UPDATE_NOTIFIER=false
        - NPM_CONFIG_FUND=false
    container_name: vcs-frontend
    hostname: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000
      - NPM_CONFIG_UPDATE_NOTIFIER=false
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - vcs-network

volumes:
  model-data: 

networks:
  vcs-network:
    driver: bridge 