version: '3.8'

services:
  backend:
    build: ./backend
    container_name: vcs-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - model-data:/app/yolo_model
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vcs-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  model-data: 